package mkfs_minix

import (
	"bytes"
	"encoding/binary"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestRunFloppy(t *testing.T) {
	var buf bytes.Buffer
	blocks := 30
	inodes := 16

	res, err := Run(&buf, blocks, inodes)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	// Verify superblock fields returned
	if res.Zones != uint16(blocks) {
		t.Errorf("expected %d zones, got %d", blocks, res.Zones)
	}

	// Output buffer size should be exactly blocks * 1024
	expectedSize := blocks * 1024
	if buf.Len() != expectedSize {
		t.Errorf("expected buffer size %d, got %d", expectedSize, buf.Len())
	}

	// Verify Superblock magic in the generated bytes (Block 1 offset 1024)
	data := buf.Bytes()
	sbOffset := 1024
	magic := binary.LittleEndian.Uint16(data[sbOffset+16 : sbOffset+18])
	if magic != 0x137F {
		t.Errorf("expected Minix V1 magic 0x137F, got 0x%04X", magic)
	}

	// Verify cleanliness state
	state := binary.LittleEndian.Uint16(data[sbOffset+18 : sbOffset+20])
	if state != 1 {
		t.Errorf("expected clean state 1, got %d", state)
	}
}

func TestRunErrorCases(t *testing.T) {
	var buf bytes.Buffer
	t.Run("too few blocks", func(t *testing.T) {
		_, err := Run(&buf, 5, 0)
		if err == nil {
			t.Error("expected error for too few blocks, got nil")
		}
	})

	t.Run("filesystem too small for metadata", func(t *testing.T) {
		_, err := Run(&buf, 10, 500)
		if err == nil {
			t.Error("expected error for too small metadata partition, got nil")
		}
	})
}

func TestMkfsMinixCLI(t *testing.T) {
	tempDir, err := os.MkdirTemp("", "mkfs_test")
	if err != nil {
		t.Fatal(err)
	}
	defer os.RemoveAll(tempDir)

	targetFile := filepath.Join(tempDir, "minix.img")

	t.Run("create floppy image", func(t *testing.T) {
		var stdout, stderr bytes.Buffer
		code := mkfsMinixRun([]string{targetFile, "40"}, &stdout, &stderr, nil, "")
		if code != 0 {
			t.Errorf("expected exit 0, got %d. stderr: %s", code, stderr.String())
		}
		got := stdout.String()
		if !strings.Contains(got, "40 blocks") || !strings.Contains(got, "Firstdatazone=") {
			t.Errorf("expected valid stats output, got %q", got)
		}
	})

	t.Run("create floppy image JSON", func(t *testing.T) {
		var stdout, stderr bytes.Buffer
		code := mkfsMinixRun([]string{"--json", targetFile, "40"}, &stdout, &stderr, nil, "")
		if code != 0 {
			t.Errorf("expected exit 0, got %d. stderr: %s", code, stderr.String())
		}
		got := stdout.String()
		if !strings.Contains(got, `"imap_blocks"`) || !strings.Contains(got, `"first_data_zone"`) {
			t.Errorf("expected valid JSON output, got %q", got)
		}
	})

	t.Run("missing target", func(t *testing.T) {
		var stdout, stderr bytes.Buffer
		code := mkfsMinixRun([]string{}, &stdout, &stderr, nil, "")
		if code != 2 {
			t.Errorf("expected exit 2, got %d", code)
		}
	})
}
